version: '3.6'

services:
  dragons-flame:
    build: .
    container_name: dragons-flame
    volumes:
      - dragons_flame_data:/app/data
      # Uncomment the line below for Docker integration
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5005:5005"
    environment:
      - PASSWORD=dragons_flame_password
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "com.dragons-flame.version=2.4.0"
      - "com.dragons-flame.features=import-export,data-management"

volumes:
  dragons_flame_data:
    driver: local