apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: dragons-flame
build:
  artifacts:
  - image: kwslavens74/dragons-flame
    context: .
    sync:
      manual:
      - src: controllers/*.js
        dest: .
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: kwslavens74/dragons-flame
      sync:
        manual:
        - src: controllers/*.js
          dest: .
      docker:
        dockerfile: Dockerfile.dev
- name: shokohsc
  build:
    artifacts:
    - image: kwslavens74/dragons-flame
      sync:
        manual:
        - src: controllers/*.js
          dest: .
      kaniko:
        dockerfile: Dockerfile.dev
        cache:
          repo: kwslavens74/dragons-flame
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
  deploy:
    kustomize:
      paths:
      - k8s/overlays/shokohsc
- name: prod
  build:
    artifacts:
    - image: kwslavens74/dragons-flame
      kaniko:
        dockerfile: Dockerfile
        cache:
          repo: kwslavens74/dragons-flame
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
